trigger:
    branches:
         include:
         - master
    paths:
          exclude:
          - README.md
          - Scripts/*
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NugetFeed: 'https://api.nuget.org/v3/index.json'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'    
    packagesToPack: '**/Source/*/*.csproj'
    configuration: '$(buildConfiguration)'
    projects: '**/Source/*/*.csproj'
    modifyOutputPath: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

