trigger:
    branches:
         include:
         - master
    paths:
          exclude:
          - README.md
          - Scripts/*
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NugetFeed: 'https://api.nuget.org/v3/index.json'

steps:
- task: UseDotNet@2
  displayName: Install .Net SDK 3.1.x
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    
- task: DotNetCoreCLI@2
  displayName: Build Source And Tests - Release
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: |
     **/Source/*/*.csproj
     **/Tests/*/*.csproj

- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    runSettingsFile: 'Scripts/DickinsonBros.Encryption.Certificate.runsettings'

- task: DotNetCoreCLI@2
  displayName: Pack Source Release
  inputs:
    command: 'pack'
    packagesToPack: '**/Source/*/*.csproj'
    configuration: '--configuration $(buildConfiguration)'